[package]
name = "frust"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
clap = { version = "4.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
rayon = "1.7.0"
